version: '3.8'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
    environment:
      - TZ=Asia/Dubai
    restart: unless-stopped
    network_mode: host
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
#      - /dev/ttyUSB1:/dev/ttyUSB1
#      - /dev/ttyACM0:/dev/ttyACM0


  home-panel:
    container_name: home-panel
    image: timmo001/home-panel
    environment:
      SSL_CERTFILE: fullchain.pem
      SSL_KEYFILE: privkey.pem
    ports:
      - 8234:8234
    volumes:
      - ./home_panel_data:/data
      - ~/addons/letsencrypt/config/keys/letsencrypt/fullchain.pem:/data/ssl/fullchain.pem:ro
      - ~/addons/letsencrypt/config/keys/letsencrypt/privkey.pem:/data/ssl/privkey.pem:ro


volumes:
  home_panel_data: {}
