alarm_code: secret_alarm_code

snapcast_server: secret_snapcast_server
snapcast_port: secret_snapcast_port
mpd_rpc_path: secret_mpd_rpc_path

transmission_host: secret_transmission_host
transmission_port: secret_transmission_port
transmission_username: secret_transmission_username
transmission_password: secret_transmission_password

google_client_secret: secret_google_client_secret
google_project_id: secret_google_project_id
google_pin: secret_google_pin
google_api_key: secret_google_api_key

homekit_pin: secret_homekit_pin

ifttt_key: secret_ifttt_key

broadlink_host: secret_broadlink_host
broadlink_mac: secret_broadlink_mac

sonoff_user: secret_sonoff_user
sonoff_pass: secret_sonoff_pass

home_ltd: secret_home_ltd
home_lng: secret_home_lng
work_ltd: secret_work_ltd
work_lng: secret_work_lng
here_api_key: secret_here_api_key

withings_client_id: secret_withings_client_id
withings_client_secret: secret_withings_client_secret