network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0:
      dhcp4: false
      dhcp6: false
      addresses:
        - local_ip/24
      gateway4: local_gateway
      nameservers:
          addresses: [8.8.8.8, 1.1.1.1, 208.67.222.222]
